name: CD - Tag, Changelog, Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Bump Version and Push Tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: minor
        RELEASE_BRANCHES: main

    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        tag: ${{ steps.tag_version.outputs.new_tag }}
